
import java.awt.Color;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Hp
 */
public class Playlist extends javax.swing.JFrame {

    /**
     * Creates new form Playlist
     */
    boolean toggle = false;

    public Playlist() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        volume_slider.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomePanel = new javax.swing.JPanel();
        NavBar = new javax.swing.JPanel();
        HomePageButton = new javax.swing.JButton();
        MusicPageButton = new javax.swing.JButton();
        PlayListPageButton = new javax.swing.JButton();
        ControlPanel = new javax.swing.JPanel();
        MusicSlider = new javax.swing.JSlider();
        PreviousButton = new javax.swing.JButton();
        PlayButton = new javax.swing.JButton();
        NextButton = new javax.swing.JButton();
        volume_slider = new javax.swing.JSlider();
        VolumeButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HomePanel.setBackground(new java.awt.Color(102, 153, 255));

        NavBar.setBackground(new java.awt.Color(102, 153, 255));

        HomePageButton.setBackground(new java.awt.Color(255, 0, 0));
        HomePageButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        HomePageButton.setForeground(new java.awt.Color(255, 255, 255));
        HomePageButton.setText("Home");
        HomePageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomePageButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomePageButtonMouseExited(evt);
            }
        });
        HomePageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomePageButtonActionPerformed(evt);
            }
        });

        MusicPageButton.setBackground(new java.awt.Color(255, 0, 0));
        MusicPageButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        MusicPageButton.setForeground(new java.awt.Color(255, 255, 255));
        MusicPageButton.setText("Music");
        MusicPageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MusicPageButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MusicPageButtonMouseExited(evt);
            }
        });
        MusicPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusicPageButtonActionPerformed(evt);
            }
        });

        PlayListPageButton.setBackground(new java.awt.Color(255, 0, 0));
        PlayListPageButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        PlayListPageButton.setForeground(new java.awt.Color(255, 255, 255));
        PlayListPageButton.setText("PlayList");
        PlayListPageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PlayListPageButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PlayListPageButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout NavBarLayout = new javax.swing.GroupLayout(NavBar);
        NavBar.setLayout(NavBarLayout);
        NavBarLayout.setHorizontalGroup(
            NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NavBarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HomePageButton)
                            .addComponent(MusicPageButton)))
                    .addComponent(PlayListPageButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NavBarLayout.setVerticalGroup(
            NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavBarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(HomePageButton)
                .addGap(21, 21, 21)
                .addComponent(MusicPageButton)
                .addGap(27, 27, 27)
                .addComponent(PlayListPageButton)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        ControlPanel.setBackground(new java.awt.Color(102, 153, 255));

        PreviousButton.setBackground(new java.awt.Color(255, 0, 0));
        PreviousButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        PreviousButton.setForeground(new java.awt.Color(255, 255, 255));
        PreviousButton.setText("Previous");
        PreviousButton.setPreferredSize(new java.awt.Dimension(75, 33));
        PreviousButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PreviousButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PreviousButtonMouseExited(evt);
            }
        });
        PreviousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousButtonActionPerformed(evt);
            }
        });

        PlayButton.setBackground(new java.awt.Color(255, 0, 0));
        PlayButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        PlayButton.setForeground(new java.awt.Color(255, 255, 255));
        PlayButton.setText("Play");
        PlayButton.setPreferredSize(new java.awt.Dimension(72, 33));
        PlayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PlayButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PlayButtonMouseExited(evt);
            }
        });
        PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayButtonActionPerformed(evt);
            }
        });

        NextButton.setBackground(new java.awt.Color(255, 0, 0));
        NextButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NextButton.setForeground(new java.awt.Color(255, 255, 255));
        NextButton.setText("Next");
        NextButton.setPreferredSize(new java.awt.Dimension(72, 33));
        NextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NextButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NextButtonMouseExited(evt);
            }
        });

        VolumeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/volume-down.png"))); // NOI18N
        VolumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlPanelLayout.createSequentialGroup()
                        .addComponent(VolumeButton)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlPanelLayout.createSequentialGroup()
                        .addComponent(PreviousButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(PlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(281, 281, 281))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlPanelLayout.createSequentialGroup()
                        .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MusicSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                            .addComponent(volume_slider, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))))
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MusicSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NextButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PlayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PreviousButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addComponent(volume_slider, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VolumeButton))
        );

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PlayList");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NavBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(219, 219, 219))
            .addComponent(ControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NavBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomePageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomePageButtonActionPerformed
        // TODO add your handling code here:
        HomePage h = new HomePage();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomePageButtonActionPerformed

    private void MusicPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusicPageButtonActionPerformed
        // TODO add your handling code here:
        Music m = new Music();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MusicPageButtonActionPerformed

    private void PreviousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PreviousButtonActionPerformed

    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayButtonActionPerformed
        // TODO add your handling code here:

        if ("Play".equals(PlayButton.getText())) {
            // Logic to start playing the music
            // Example: musicPlayer.play();
            PlayButton.setText("Stop");
        } else {
            // Logic to stop the music
            // Example: musicPlayer.stop();
            PlayButton.setText("Play");
        }
    }//GEN-LAST:event_PlayButtonActionPerformed

    private void VolumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumeButtonActionPerformed
        // TODO add your handling code here:
        if (toggle == false) {
            volume_slider.setVisible(true);
            toggle = true;
        } else {
            volume_slider.setVisible(false);
            toggle = false;

        }
    }//GEN-LAST:event_VolumeButtonActionPerformed

    private void MusicPageButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MusicPageButtonMouseEntered
        // TODO add your handling code here:
        MusicPageButton.setBackground(Color.green.darker());
        MusicPageButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_MusicPageButtonMouseEntered

    private void MusicPageButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MusicPageButtonMouseExited
        // TODO add your handling code here:
        MusicPageButton.setBackground(Color.red);
        MusicPageButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_MusicPageButtonMouseExited

    private void HomePageButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePageButtonMouseEntered
        // TODO add your handling code here:
        HomePageButton.setBackground(Color.green.darker());
        HomePageButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_HomePageButtonMouseEntered

    private void HomePageButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePageButtonMouseExited
        // TODO add your handling code here:
        HomePageButton.setBackground(Color.red);
        HomePageButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_HomePageButtonMouseExited

    private void PlayListPageButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayListPageButtonMouseEntered
        // TODO add your handling code here:
        PlayListPageButton.setBackground(Color.green.darker());
        PlayListPageButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_PlayListPageButtonMouseEntered

    private void PlayListPageButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayListPageButtonMouseExited
        // TODO add your handling code here:
        PlayListPageButton.setBackground(Color.red);
        PlayListPageButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_PlayListPageButtonMouseExited

    private void PreviousButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PreviousButtonMouseEntered
        // TODO add your handling code here:
        PreviousButton.setBackground(Color.green.darker());
        PreviousButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_PreviousButtonMouseEntered

    private void PreviousButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PreviousButtonMouseExited
        // TODO add your handling code here:
        PreviousButton.setBackground(Color.red);
        PreviousButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_PreviousButtonMouseExited

    private void PlayButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayButtonMouseEntered
        // TODO add your handling code here:
        PlayButton.setBackground(Color.green.darker());
        PlayButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_PlayButtonMouseEntered

    private void PlayButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayButtonMouseExited
        // TODO add your handling code here:
        PlayButton.setBackground(Color.red);
        PlayButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_PlayButtonMouseExited

    private void NextButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextButtonMouseEntered
        // TODO add your handling code here:
        NextButton.setBackground(Color.green.darker());
        NextButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_NextButtonMouseEntered

    private void NextButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextButtonMouseExited
        // TODO add your handling code here:
        NextButton.setBackground(Color.red);
        NextButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_NextButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Playlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Playlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Playlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Playlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Playlist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JButton HomePageButton;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JButton MusicPageButton;
    private javax.swing.JSlider MusicSlider;
    private javax.swing.JPanel NavBar;
    private javax.swing.JButton NextButton;
    private javax.swing.JButton PlayButton;
    private javax.swing.JButton PlayListPageButton;
    private javax.swing.JButton PreviousButton;
    private javax.swing.JButton VolumeButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider volume_slider;
    // End of variables declaration//GEN-END:variables
}
